"""Frontend-independent analysis API."""

from .abaqus_dependent import (
    AbaqusDamagePolicy,
    AbaqusDependentMode,
    AbaqusLegacyDependentRequest,
    AbaqusLegacyDependentResult,
    AbaqusLegacyDependentValidationError,
    abaqus_legacy_dependent_material_text,
    build_abaqus_legacy_dependent_material_text,
    rate_mapping_audit_rows,
    run_abaqus_legacy_dependent_material,
    temperature_elastic_audit_rows,
)
from .abaqus_legacy import (
    ABAQUS_LEGACY_FULL_CALIBRATION_ID,
    AbaqusCdpProvenance,
    AbaqusCdpSourceKind,
    AbaqusLegacyInputError,
    AbaqusLegacyMaterialRequest,
    AbaqusLegacyMaterialResult,
    AbaqusLegacyValidationError,
    abaqus_legacy_material_text,
    build_abaqus_legacy_cdp_material_text,
    run_abaqus_legacy_material,
    validate_abaqus_legacy_material_tables,
)
from .authority_catalog import (
    ProfileParameterSpec,
    available_concrete_classes,
    available_physical_profiles,
    cdpm2_override_fields,
    cdpm2_parameter_units,
    physical_profile_label,
    profile_parameter_specs,
)
from .authority_requests import (
    AuthorityConcreteRequest,
    AuthorityInputError,
    Cdpm2ConversionRequest,
    parse_cdpm2_overrides,
)
from .authority_results import (
    AuthorityConcreteResult,
    Cdpm2ConversionResult,
    PhysicalPropertyRecord,
)
from .authority_services import (
    Cdpm2SofteningInvariantError,
    build_authority_concrete,
    cdpm2_tensile_softening_curves,
    fib_mc2010_fracture_energy_composition,
    run_cdpm2_conversion,
)
from .comparison import (
    ComparisonCase,
    ComparisonInputError,
    add_comparison_case,
    authority_comparison_tables,
    compatible_curve_groups,
    curve_semantic_signature,
    make_comparison_case,
    rename_comparison_case,
    steel_comparison_table,
)
from .requests import LegacyConcreteAnalysisRequest
from .results import CurveSeries, PropertyValue, ResultBundle
from .services import result_excel_bytes, run_legacy_concrete_analysis, temperature_cases
from .steel_catalog import available_steel_grades, available_steel_standards
from .steel_requests import SteelAnalysisRequest, SteelInputError, parse_float_series
from .steel_results import SteelAnalysisResult
from .steel_services import run_steel_analysis, steel_result_abaqus_text, steel_result_excel_bytes

__all__ = [
    "ABAQUS_LEGACY_FULL_CALIBRATION_ID",
    "AbaqusCdpProvenance",
    "AbaqusCdpSourceKind",
    "AbaqusDamagePolicy",
    "AbaqusDependentMode",
    "AbaqusLegacyDependentRequest",
    "AbaqusLegacyDependentResult",
    "AbaqusLegacyDependentValidationError",
    "AbaqusLegacyInputError",
    "AbaqusLegacyMaterialRequest",
    "AbaqusLegacyMaterialResult",
    "AbaqusLegacyValidationError",
    "AuthorityConcreteRequest",
    "AuthorityConcreteResult",
    "AuthorityInputError",
    "Cdpm2ConversionRequest",
    "Cdpm2ConversionResult",
    "Cdpm2SofteningInvariantError",
    "ComparisonCase",
    "ComparisonInputError",
    "CurveSeries",
    "LegacyConcreteAnalysisRequest",
    "PhysicalPropertyRecord",
    "ProfileParameterSpec",
    "PropertyValue",
    "ResultBundle",
    "SteelAnalysisRequest",
    "SteelAnalysisResult",
    "SteelInputError",
    "abaqus_legacy_dependent_material_text",
    "abaqus_legacy_material_text",
    "add_comparison_case",
    "authority_comparison_tables",
    "available_concrete_classes",
    "available_physical_profiles",
    "available_steel_grades",
    "available_steel_standards",
    "build_abaqus_legacy_cdp_material_text",
    "build_abaqus_legacy_dependent_material_text",
    "build_authority_concrete",
    "cdpm2_override_fields",
    "cdpm2_parameter_units",
    "cdpm2_tensile_softening_curves",
    "compatible_curve_groups",
    "curve_semantic_signature",
    "fib_mc2010_fracture_energy_composition",
    "make_comparison_case",
    "parse_cdpm2_overrides",
    "parse_float_series",
    "physical_profile_label",
    "profile_parameter_specs",
    "rate_mapping_audit_rows",
    "rename_comparison_case",
    "result_excel_bytes",
    "run_abaqus_legacy_dependent_material",
    "run_abaqus_legacy_material",
    "run_cdpm2_conversion",
    "run_legacy_concrete_analysis",
    "run_steel_analysis",
    "steel_comparison_table",
    "steel_result_abaqus_text",
    "steel_result_excel_bytes",
    "temperature_cases",
    "temperature_elastic_audit_rows",
    "validate_abaqus_legacy_material_tables",
]
